---
title: "Ödev 1"
author: "Ad Soyad"
---

```{r global_options, include=FALSE}
# Bu kod blogununun icerigini degistirmeyiniz, silmeyiniz.
library(knitr)
library(ggplot2)
opts_chunk$set(fig.align="center", fig.height=4, fig.width=5.5)
```

**Soru 1** Markdown kullanarak bir kelimesi kalın olan bir cümle yazınız.

Cevabınızı buraya yazınız!

**Soru 2** Markdown kullanarak bir kelimesi italik olan bir cümle yazınız.

Cevabınızı buraya yazınız!

**Soru 3** Markdown kullanarak bir kelimesi kalın italik olan bir cümle yazınız.

Cevabınızı buraya yazınız!

**Soru 4** Markdown kullanarak 3 elemanlı bir sırasız liste yazınız.

Cevabınızı buraya yazınız!

**Soru 5** Markdown kullanarak 3 elemanlı bir sıralı liste yazınız.

Cevabınızı buraya yazınız!

**Soru 6** Markdown kullanarak istediğiniz bir websayfasına link veriniz.

Cevabınızı buraya yazınız!

**Soru 7** Markdown kullanarak bir komik bir kedi fotoğrafı ekleyiniz.

Cevabınızı buraya yazınız!

**Soru 8** RMarkdown kullanarak bir kod bloğu ekleyiniz ve içerisinde basit bir matematik işlemi yapınız.

Cevabınızı buraya yazınız!

**Soru 9** LaTeX kullanarak bir blok denklem yazınız

Cevabınızı buraya yazınız!

**Soru 9** Bir kod bloğu ekleyerek 5 + 4 toplamını hesaplayınız.

Cevabınızı buraya yazınız!
